### PR TITLE
Fix hypervisor disconnection issue.

### LINKED ISSUE #346: Hypervisor is not retrying discovery registration
**Describe the bug**
@evanlinjin reported that the hypervisor did not retry registering itself in the dmsg.Discovery and therefore visors could not connect. 

The hypervisor should try to register itself in the discovery continually with a backoff.

### PR DESCRIPTION
**Pull request by evanlinjin**
Fixes #346

 Changes:	
-	 Added a timeout to `visor.RPCClient` in which it closes the underlying connection.

To do:
- [x] Test this.

### CODE REVIEW

File: pkg/visor/rpc_client.go [hunk 1]
```diff
@@ -4,12 +4,15 @@ import (
...
 	"fmt"
+	"io"
 	"math/rand"
 	"net/http"
 	"net/rpc"
 	"sync"
 	"time"
 
+	"github.com/sirupsen/logrus"
+
```
Comment (nkryuchkov) [inline pkg/visor/rpc_client.go]: Could you please format imports?

File: pkg/visor/rpc_client_serve.go [hunk 2]
```diff
@@ -22,9 +23,13 @@ func isDone(ctx context.Context) bool {
 
 // ServeRPCClient repetitively dials to a remote dmsg address and serves a RPC server to that address.
 func ServeRPCClient(ctx context.Context, log logrus.FieldLogger, n *snet.Network, rpcS *rpc.Server, rAddr dmsg.Addr, errCh chan<- error) {
+
+	const MaxBackoff = time.Second * 5
```
Comment (nkryuchkov) [inline pkg/visor/rpc_client_serve.go]: Could you please change the first letter to lowercase?

**Review by nkryuchkov — APPROVED** [review]
Great job!

**Review by jdknives — APPROVED** [review]
