### PR TITLE
Versioned visor configs.

### LINKED ISSUE #362: Properly implement versioned visor config.
@nkryuchkov I'm thinking of moving config into a separate module, maybe `/pkg/visor/visorconfig` and having versioned structs. E.g. `visorconfig.V1` or something.

Proposed features:
* Struct per config version.
* Common interface for all config versions.
* Ability to *upgrade* a config file.
* Ability to read in an older config version.

_Originally posted by @evanlinjin in https://github.com/SkycoinProject/skywire-mainnet/pull/360/review_comment/create_

### LINKED ISSUE #365: Get back `-t` flag for `skywire-cli visor gen-config`
**Describe the bug**
There was previously an ability to generate test config for visor with `skywire-cli visor gen-config -t`. This flag was accidentally removed by latest changes and should be returned.

### PR DESCRIPTION
**Pull request by evanlinjin**
Fixes #362 Fixes #365 

 Changes:	
* Moved visor conifg-related parts to a new module /pkg/visor/visorconfig.
* Introduced visorconfig.Common that contains shared fields across all config versions.
* Improved config-parsing logic.

To do:
- [x] Visor shutdown order should be inverted.
- [x] Implement default `testenv` config generation.
- [x] Implement config upgrading from `v0.0.0`.
- [x] Fix CLI: https://discordapp.com/channels/466450852098605059/466450852098605061/711893952856457237
    ```
    $ ./skywire-cli visor add-tp 0219bec686b86f828bd1995d6c5c8587aa6d55a3f1ae88951eda0890ca456e4d08 --type dmsg
    [2020-05-18T13:46:12+03:00] FATAL [skywire-cli]: Failed to establish dmsg transport error="rpc client timeout"
    ```
- [x] Write tests.
- [x] Add `pk` back into visor config.
- [x] Make all package loggers respect master logger settings.

How to test this PR:
* `make check`
* `skywire-cli visor gen-config` (test with different combinations of flags)
* `skywire-visor` with an older config version (e.g. from `master` branch)

### CODE REVIEW

File: ci_scripts/install-golangci-lint.sh [hunk 1]
```diff
@@ -10,6 +10,9 @@ if [[ "$VERSION" != "latest" ]]; then
   VERSION="v$VERSION"
 fi
 
+[[ -z "${GOBIN}" ]] export GOBIN=$HOME/go/bin
```
Comment (nkryuchkov) [inline ci_scripts/install-golangci-lint.sh]: Would you mind putting that into an `if` statement? I think it would look easier to understand.

File: cmd/skywire-cli/commands/visor/gen-config.go [hunk 2]
```diff
@@ -2,90 +2,104 @@ package visor
 
 import (
 	"encoding/json"
-	"fmt"
 	"io/ioutil"
-	"path"
+	"os"
 	"path/filepath"
 
+	"github.com/SkycoinProject/skycoin/src/util/logging"
```
Comment (nkryuchkov) [inline cmd/skywire-cli/commands/visor/gen-config.go:9]: Could you please sort them?

File: cmd/skywire-visor/commands/root.go [hunk 3]
```diff
@@ -2,235 +2,169 @@ package commands
...
-	"encoding/json"
+	"context"
 	"fmt"
 	"io"
 	"io/ioutil"
-	"log"
 	"log/syslog"
 	"net/http"
-	_ "net/http/pprof" // nolint:gosec // TODO: consider removing for security reasons
+	_ "net/http/pprof" // nolint:gosec https://golang.org/doc/diagnostics.html#profiling
```
Comment (nkryuchkov) [inline cmd/skywire-visor/commands/root.go]: Line 3 may be removed.

File: cmd/skywire-visor/commands/root.go [hunk 4]
```diff
@@ -2,235 +2,169 @@ package commands
...
+	rootCmd.Flags().StringVar(&syslogAddr, "syslog", "", "syslog server address. E.g. localhost:514")
+	rootCmd.Flags().StringVarP(&pprofMode, "pprofmode", "p", "", "pprof profiling mode. Valid values: cpu, mem, mutex, block, trace, http")
+	rootCmd.Flags().StringVar(&pprofAddr, "pprofaddr", "localhost:6060", "pprof http port if mode is 'http'")
+	rootCmd.Flags().StringVarP(&confPath, "config", "c", "skywire-config.json", "config file location. If the value is 'STDIN', config file will be read from stdin.")
+}
 
 var rootCmd = &cobra.Command{
 	Use:   "skywire-visor [config-path]",
-	Short: "Visor for skywire",
+	Short: "Skywire visor.",
```
Comment (nkryuchkov) [inline cmd/skywire-visor/commands/root.go]: Is dot obligatory here?

File: cmd/skywire-visor/commands/root.go [hunk 5]
```diff
@@ -2,235 +2,169 @@ package commands
...
 	Run: func(_ *cobra.Command, args []string) {
-		if _, err := buildinfo.Get().WriteTo(log.Writer()); err != nil {
-			log.Printf("Failed to output build info: %v", err)
+
+		log := initLogger(tag, syslogAddr)
+
+		if _, err := buildinfo.Get().WriteTo(log.Out); err != nil {
+			log.WithError(err).Error("Failed to obtain build info.")
```
Comment (nkryuchkov) [inline cmd/skywire-visor/commands/root.go]: What do you think of changing `obtain` back to `output` because the error indicates an error while outputting build info?

File: pkg/visor/init.go [hunk 6]
```diff
@@ -10,6 +10,8 @@ import (
 	"sync"
 	"time"
 
+	"github.com/SkycoinProject/skywire-mainnet/pkg/visor/visorconfig"
```
Comment (nkryuchkov) [inline pkg/visor/init.go]: Not sorted.

File: pkg/visor/rpc_test.go [hunk 7]
```diff
@@ -6,6 +6,8 @@ import (
 	"testing"
 	"time"
 
+	"github.com/SkycoinProject/skywire-mainnet/pkg/visor/visorconfig"
```
Comment (nkryuchkov) [inline pkg/visor/rpc_test.go:9]: Not sorted.

File: pkg/visor/visor.go [hunk 8]
```diff
@@ -12,6 +12,8 @@ import (
 	"syscall"
 	"time"
 
+	"github.com/SkycoinProject/skywire-mainnet/pkg/visor/visorconfig"
```
Comment (nkryuchkov) [inline pkg/visor/visor.go:15]: Not sorted.

File: pkg/visor/visorconfig/common.go [hunk 9]
```diff
@@ -0,0 +1,101 @@
...
+	path string
+	log  *logging.MasterLogger
+
+	Version string        `json:"version"`
+	SK      cipher.SecKey `json:"sk,omitempty"`
+	pk      cipher.PubKey
+}
+
+// NewCommon returns a new Common.
+func NewCommon(log *logging.MasterLogger, confPath string, version string, sk *cipher.SecKey) (*Common, error) {
```
Comment (nkryuchkov) [inline pkg/visor/visorconfig/common.go]: To reduce line length, I'd write `confPath, version string`.

File: cmd/skywire-cli/commands/visor/gen-config.go (hunk 2 above)
Comment (evanlinjin) [reply cmd/skywire-cli/commands/visor/gen-config.go:9]: @nkryuchkov I feel like we shouldn't be spending time manually sorting imports. I know they are atrocious to look at, but let's wait until the `go generate` solution gets implemented.

File: pkg/visor/visorconfig/parse_test.go [hunk 10]
```diff
@@ -0,0 +1,49 @@
...
+	"io/ioutil"
+	"os"
+	"testing"
+
+	"github.com/SkycoinProject/dmsg/cipher"
+	"github.com/stretchr/testify/require"
+)
+
+func TestParse(t *testing.T) {
+
```
Comment (Darkren) [inline pkg/visor/visorconfig/parse_test.go]: Could you remove this empty line please?

**Review by Darkren — CHANGES_REQUESTED** [review]
Otherwise, great job? Also, could you please run latest `readmegen` to generate readme for new config?
