### PR TITLE
Fix bool flag config representation

### LINKED ISSUE #691: Flag order affects VPN behavior
**Describe the bug**
If the `-killswitch` flag is set first, before `-srv` or `-passcode`, the VPN-client does not work as the flags after the `-killswitch` are not read bz or not provided to the VPN-client. 

Consequently this fails 

```
[
					"-killswitch",
					"true",
					"-passcode",
					"",
					"-srv",
					"02e346d917500aadb71c8b0eafb4125c0e03723a0671dc7352cdd106ab215ef8e5"
				],
```

While this works:

```
[
					"-passcode",
					"",
					"-srv",
					"02e346d917500aadb71c8b0eafb4125c0e03723a0671dc7352cdd106ab215ef8e5",
					"-killswitch",
					"true"
				],
```

### PR DESCRIPTION
**Pull request by Darkren**
Did you run `make format && make check`?

Fixes #691 

 Changes:	
- All boolean flags that we support are now represented in format of `--flag_name=value` in the app args.

### CODE REVIEW

File: pkg/visor/visorconfig/v1.go [hunk 1]
```diff
@@ -151,32 +160,108 @@ func (v1 *V1) UpdateAppArg(launch *launcher.Launcher, appName, argName, value st
...
+
+	configChanged := false
+
+	for i := range conf.Apps {
+		if conf.Apps[i].Name != appName {
+			continue
+		}
+
+		// we format it to have two dashes, just to unify representation
+		fmtedArgName := argName
```
Comment (jdknives) [inline pkg/visor/visorconfig/v1.go:220]: Would it not be cleaner to stick with single dashes? Maybe it does not look as nice, but works just as well.

**Review by jdknives — APPROVED** [review]
Looking good. Just one suggestion.

**Comment by jdknives** [comment]
[log.txt](https://github.com/skycoin/skywire/files/6037160/log.txt)

We are also running into a panic when updating the secure mode on an empty VPN server arg list.

File: pkg/visor/visorconfig/v1.go (hunk 1 above)
Comment (Darkren) [reply pkg/visor/visorconfig/v1.go:220]: It doesn't really matter at all, so will do
