### PR TITLE
Fix locking order.

### LINKED ISSUE #553: Hypervisor connection shutdown while dialing stcpr
**Describe the bug**
Currently the AR is not functional because of the deployment setup. Therefore, when dialing an `stcpr` transport the visor gets a timeout. For the time that the visor is waiting on the timeout, the frontend becomes unusable. 

For context the timeout logs here:
```
[2020-10-19T10:39:17+03:00] INFO [tp:02f9c5]: Serving. remote_pk=02f9c5ebd8e480d33b0de67555089bcd85cc1d70c70a17fa5827159c0fcf0a755c tp_id=225c9e19-8c42-0538-b4b1-3584ff9e7783 tp_index=1
[2020-10-19T10:39:17+03:00] INFO [stcpr]: Dialing PK 02f9c5ebd8e480d33b0de67555089bcd85cc1d70c70a17fa5827159c0fcf0a755c
[2020-10-19T10:39:17+03:00] INFO [stcpr]: Resolved PK 02f9c5ebd8e480d33b0de67555089bcd85cc1d70c70a17fa5827159c0fcf0a755c to visor data {192.168.255.50 false {43947 [127.0.0.1 172.104.158.4 ::1 2a01:7e01::f03c:92ff:fe39:e541]}}
[2020-10-19T10:40:33+03:00] WARN [transport_manager]: Underlying transport connection is not established, will retry later. error="snet.Dial: dial: dial tcp 192.168.255.50:43947: connect: operation timed out"
```

Hypervisor logs:
```
2020/10/19 10:46:42 [Rudis-MacBook-Pro.local/VaZMFsRSuA-000374] "GET http://localhost:8000/api/visors/02d941663f4b35a932ef803c6de022c54c030dfbd7d8d75afd25d52a5d5392276e HTTP/1.1" from 127.0.0.1:63725 - 500 38B in 20.0004784s
2020/10/19 10:46:42 [Rudis-MacBook-Pro.local/VaZMFsRSuA-000373] "POST http://localhost:8000/api/visors/02d941663f4b35a932ef803c6de022c54c030dfbd7d8d75afd25d52a5d5392276e/transports HTTP/1.1" from 127.0.0.1:63687 - 500 16B in 23.279451209s
2020/10/19 10:46:47 [Rudis-MacBook-Pro.local/VaZMFsRSuA-000375] "GET http://localhost:8000/api/visors/02d941663f4b35a932ef803c6de022c54c030dfbd7d8d75afd25d52a5d5392276e HTTP/1.1" from 127.0.0.1:63687 - 500 36B in 60.917µs
2020/10/19 10:46:52 [Rudis-MacBook-Pro.local/VaZMFsRSuA-000376] "GET http://localhost:8000/api/visors/02d941663f4b35a932ef803c6de022c54c030dfbd7d8d75afd25d52a5d5392276e HTTP/1.1" from 127.0.0.1:63687 - 500 36B in 70.388µs
```

After the dial timed out, the hypervisor functions again.

**Environment information:**

- OS: MacOS
- `develop`  branch

**Steps to Reproduce**

Open up hypervisor UI with visor and try to estbalish `stcpr` with address resolver. It is import to use a remote that is registered in the address resolver but cannot be reached.

### PR DESCRIPTION
**Pull request by taras-skycoin**
Did you run `make format && make check`?
Yes
Fixes #553
Unresponsiveness when you try to connect to the unreachable visor 
 Changes:	
-	Changed order of locking

How to test this PR:
Block traffic from your IP on the remote visor and try to establish `stcpr` transport via UI and check if other requests to API procccessed in adequate time.

### CODE REVIEW

File: pkg/transport/manager.go [hunk 1]
```diff
@@ -297,7 +299,11 @@ func (tm *Manager) SaveTransport(ctx context.Context, remote cipher.PubKey, tpTy
 				if closeErr := mTp.Close(); closeErr != nil {
 					tm.Logger.WithError(err).Warn("Closing mTp returns non-nil error.")
 				}
+				tm.mx.Lock()
 				delete(tm.tps, mTp.Entry.ID)
+
```
Comment (Darkren) [inline pkg/transport/manager.go]: Could you please remove this empty line?

File: pkg/transport/manager.go [hunk 2]
```diff
@@ -356,10 +362,9 @@ func (tm *Manager) saveTransport(remote cipher.PubKey, netName string) (*Managed
 		mTp.Serve(tm.readCh)
 		tm.mx.Lock()
 		delete(tm.tps, mTp.Entry.ID)
-		tm.mx.Unlock()
+		defer tm.mx.Unlock()
```
Comment (Darkren) [inline pkg/transport/manager.go]: Is `defer` needed here? it's the last statement in the function

**Review by Darkren — CHANGES_REQUESTED** [review]
Overall, great job! Totally functional. Just some minor comments. Also, there's one suggestion. With mutex we use only `saveTransport` or `delete(tm.tps, ...)`. What do you think if we move lock/deferred-unlock inside `saveTransport`? Also we could add a separate function for removing transport and also move lock/deferred-unlock inside that function. this will simplify the code

**Review by nkryuchkov — APPROVED** [review]

File: pkg/transport/manager.go [hunk 3]
```diff
@@ -297,7 +293,7 @@ func (tm *Manager) SaveTransport(ctx context.Context, remote cipher.PubKey, tpTy
 				if closeErr := mTp.Close(); closeErr != nil {
 					tm.Logger.WithError(err).Warn("Closing mTp returns non-nil error.")
 				}
-				delete(tm.tps, mTp.Entry.ID)
+				tm.DeleteTransport(mTp.Entry.ID)
```
Comment (Darkren) [inline pkg/transport/manager.go]: I'm not sure that it's safe to call `DeleteTransprot` here. Previously we just removed tp from the internal map here, while `DeleteTransport` also has responsibility to remove it from discovery which is not intended here I guess. Also `DeleteTransport` tries to close tp which is already closed at the point of this call. I guess it would be better to add a separate func starting with lowercase character like `deleteTransport` which just removes tp from the map under lock. Also this func should be called below in a goroutine on line 355

**Review by Darkren — APPROVED** [review]
