### PR TITLE
Fix stun client datarace

### LINKED ISSUE #1236: Datarace in stunclient
**Describe the bug**
A rare datarace for the module stunclient.

**Environment information:**

- OS: e.g. Linux
- Platform: Linux 5.13.0-44-generic x86_64
- 
**Steps to Reproduce**

1. Add the line `time.Sleep(time.Second * 5)` before [this](https://github.com/skycoin/skywire/blob/89b22ba8f9b21f7c51ec51f4c5f72fcb01a23f75/pkg/visor/init.go#L287) 
2. Build the visor with `-race` flag
3. Start the visor
4. Open UI and keep refreshing
5. See datarace in logs

**Actual behavior**
[log (3).txt](https://github.com/skycoin/skywire/files/8795945/log.3.txt)

### PR DESCRIPTION
**Pull request by ersonp**
Did you run `make format && make check`?
yes

Fixes #1236 

 Changes:	
- Added stunReady and stunReadyOnce to Visor
- Removed wgStunClient from Visor

How to test this PR:
1. Add the line `time.Sleep(time.Second * 5)` before [this](https://github.com/skycoin/skywire/blob/89b22ba8f9b21f7c51ec51f4c5f72fcb01a23f75/pkg/visor/init.go#L287) 
2. Build the visor with `-race` flag
3. Start the visor
4. Open UI and keep refreshing

### CODE REVIEW

File: pkg/visor/init.go [hunk 1]
```diff
@@ -279,12 +279,13 @@ func initDiscovery(ctx context.Context, v *Visor, log *logging.Logger) error {
 }
 
 func initStunClient(ctx context.Context, v *Visor, log *logging.Logger) error {
-	defer v.wgStunClient.Done()
 
 	sc := network.GetStunDetails(v.conf.StunServers, log)
 	v.initLock.Lock()
 	v.stunClient = sc
+	time.Sleep(time.Second * 5)
```
Comment (mrpalide) [inline pkg/visor/init.go]: Seems you forgot to remove this, isn't?

**Review by mrpalide — APPROVED** [review]
No data race be there, its OK, but seems a line should remove.

File: pkg/visor/init.go (hunk 1 above)
Comment (ersonp) [reply pkg/visor/init.go]: Removed
