### PR TITLE
Use logging package from skycoin for retrier

### LINKED ISSUE #1133: No dmsg servers found warning on vpn-server and vpn-client
**Describe the bug**
The logs show a warning in running `vpn-server` and `vpn-client` app when dmsg not connected.

**Environment information:**

- OS: e.g. Linux, Windows
- Platform: Linux 5.13.0-35-generic x86_64, Windows 10

**Steps to Reproduce**

1. When dmsg not established, trying to run VPN-Server or VPN-Client.

**Actual behavior**
VPN Server logs
```
[2022-03-15T16:26:21+05:30] INFO [transport_setup]: Connected! local_pk=02aa6fc7009d31622705cb3f2feaa8fe0da10c2ae081cf52e7ba7672bf097defad
[2022-03-15T16:26:21+05:30] INFO [transport_setup]: starting listener dmsg_port=47
[2022-03-15T16:26:21+05:30] INFO [transport_setup]: Accepting dmsg streams. dmsg_port=47
WARN[0001] Retrying...                                   current_backoff=1s error="no dmsg servers found" func=retrier
[2022-03-15T16:26:22+05:30] INFO [launcher]: Initialized in 1.008228687s (1.382727959s with dependencies)
[2022-03-15T16:26:22+05:30] INFO [proc_manager]: Accepted proc conn. hello="{"proc_key":"f449afebc75146b7b897b83279ab1ffe"}" remote=127.0.0.1:52216
[2022-03-15T16:26:22+05:30] INFO [proc:vpn-server:f449afebc75146b7b897b83279ab1ffe]: Associated and serving proc conn.
[2022-03-15T16:26:22+05:30] INFO [proc:vpn-server:f449afebc75146b7b897b83279ab1ffe]: Request processed. _elapsed="838.883µs" _method="Listen" _received="4:26PM" input=02aa6fc7009d31622705cb3f2feaa8fe0da10c2ae081cf52e7ba7672bf097defad:44 output=0xc00030723e
[2022-03-15T16:26:22+05:30] INFO (STDOUT) [proc:skychat:f8250d3c51da4ae1967f13a648c22d92]: Version "v0.6.0-72-gc3a95580" built on "2022-03-15T10:55:45Z" against commit "c3a955802d3c3042c31c84c294bd149f5547f4fb"
[2022-03-15T16:26:22+05:30] INFO [proc:skychat:f8250d3c51da4ae1967f13a648c22d92]: Associated and serving proc conn.
```

VPN Client logs
```
[2022-04-08T17:19:53+04:30] INFO [public_autoconnect]: Fetching public visors
[2022-04-08T17:19:54+04:30] INFO [visor]: Changing vpn-client password to ""
[2022-04-08T17:19:54+04:30] INFO [visor:config]: Flushing config to file. config_version="v0.4.1-1743-g7326eaec" filepath="skywire-config.json"
[2022-04-08T17:19:54+04:30] INFO [visor]: Updated vpn-client password
[2022-04-08T17:19:54+04:30] INFO [visor]: Changing vpn-client PK to "03065072ed9f242ab0bf857483200ba5d63122bffbc47618d81b8d58e8c2baf44e"
[2022-04-08T17:19:54+04:30] INFO [visor:config]: Flushing config to file. config_version="v0.4.1-1743-g7326eaec" filepath="skywire-config.json"
[2022-04-08T17:19:54+04:30] INFO [visor]: Updated vpn-client PK
2022/04/08 17:19:54 [DESKTOP-818V7UH/eO7ZjvvBaK-000040] "PUT http://127.0.0.1:8000/api/visors/03065072ed9f242ab0bf857483200ba5d63122bffbc47618d81b8d58e8c2baf44e/apps/vpn-client HTTP/1.1" from 127.0.0.1:61995 - 200 83B in 3.2668ms
[2022-04-08T17:19:55+04:30] INFO [dmsg_trackers]: failed to re-create dmsgtracker client error="dmsg error 100 - entry is not found in discovery"
[2022-04-08T17:19:55+04:30] INFO [dmsg_trackers]: failed to re-create dmsgtracker client error="dmsg error 100 - entry is not found in discovery"
2022/04/08 17:19:55 [DESKTOP-818V7UH/eO7ZjvvBaK-000041] "GET http://127.0.0.1:8000/api/visors/03065072ed9f242ab0bf857483200ba5d63122bffbc47618d81b8d58e8c2baf44e/summary HTTP/1.1" from 127.0.0.1:61995 - 200 955B in 1.6323277s
time="2022-04-08T17:19:56+04:30" level=warning msg=Retrying... current_backoff=1s error="no dmsg servers found" func=retrier
time="2022-04-08T17:19:57+04:30" level=warning msg=Retrying... current_backoff=1s error="no dmsg servers found" func=retrier
time="2022-04-08T17:19:58+04:30" level=warning msg=Retrying... current_backoff=1s error="no dmsg servers found" func=retrier
```

### PR DESCRIPTION
**Pull request by ersonp**
Did you run `make format && make check`?
yes

Fixes #1133 

 Changes:	
- Used logging package from `skycoin/src/util/logging`

How to test this PR:
1. Make config for test `./skywire-cli config gen -irt`
2. Run `./skywire-visor -c skywire-config.json`
3. Try to connect to a vpn-server (online vpn-server is not needed)
4. Check logs

### CODE REVIEW

**Review by mrpalide — APPROVED** [review]

File: cmd/apps/skysocks-client/skysocks-client.go [hunk 1]
```diff
@@ -28,7 +28,7 @@ const (
 	socksPort = routing.Port(3)
 )
 
-var log = logrus.New()
+var log = logging.MustGetLogger("chat")
```
Comment (mrpalide) [inline cmd/apps/skysocks-client/skysocks-client.go]: Why `chat`?

Comment (ersonp) [reply cmd/apps/skysocks-client/skysocks-client.go]: My bad. will change it.
