### PR TITLE
Make VPN work properly over stcpr

### LINKED ISSUE #517: VPN Error during route group close
**Describe the bug**
When running the VPN client, a number of errors pop up after a certain amount of time that do not break the VPN clients connection but should be investigated. The logs for the remote and the local visor are attached. 

**Environment information:**

- OS: e.g. Mac OS X

**Steps to Reproduce**

1. Setup VPN client and server
2. Setup transport between two visors
3. Run VPN client
4. Use the VPN and wait until the error pops up (took usually around a minute for me)

### PR DESCRIPTION
**Pull request by Darkren**
Did you run `make format && make check`?
Yes
Fixes #517, partially implements #383 

 Changes:	
- Callbacks for stcpr/stcp connection establishment implemented;
- These callbacks are properly used by the VPN client app;
- Remote IPs for all of the known STCPR transports are now passed to the VPN client on start;

How to test this PR:
Setup VPN connection over STCPR transport

### CODE REVIEW

**Review by jdknives — APPROVED** [review]
Works well. @nkryuchkov after you review we can merge.

File: cmd/apps/vpn-client/vpn-client.go [hunk 1]
```diff
@@ -70,7 +71,29 @@ func main() {
...
 
-	appClient := app.NewClient(nil)
+	var directIPsCh = make(chan net.IP, 100)
+
+	eventSub := appevent.NewSubscriber()
+
+	eventSub.OnTCPDial(func(data appevent.TCPDialData) {
+		log.WithField("event_type", data.Type()).
+			WithField("event_data", data).
+			Info("GOT EVENT")
```
Comment (nkryuchkov) [inline cmd/apps/vpn-client/vpn-client.go]: What do you think about changing the case of this message to the sentence case?

File: pkg/snet/network.go [hunk 2]
```diff
@@ -146,6 +146,12 @@ func New(conf Config, eb *appevent.Broadcaster) (*Network, error) {
 			SK:        conf.SecKey,
 			Table:     pktable.NewTable(conf.NetworkConfigs.STCP.PKTable),
 			LocalAddr: conf.NetworkConfigs.STCP.LocalAddr,
+			BeforeDialCallback: func(network, addr string) error {
+				data := appevent.TCPDialData{RemoteNet: network, RemoteAddr: addr}
+				event := appevent.NewEvent(appevent.TCPDial, data)
+				_ = eb.Broadcast(context.Background(), event) //nolint:errcheck
```
Comment (nkryuchkov) [inline pkg/snet/network.go:152]: Could you please explain why an error is ignored here instead of returning?

**Review by nkryuchkov — APPROVED** [review]

File: pkg/snet/network.go (hunk 2 above)
Comment (Darkren) [reply pkg/snet/network.go:152]: @nkryuchkov dial will be cancelled in case of error, cause callback is fired before dialing

File: cmd/apps/vpn-client/vpn-client.go (hunk 1 above)
Comment (Darkren) [reply cmd/apps/vpn-client/vpn-client.go]: @nkryuchkov that's debug log, just missed that, will remove
