### PR TITLE
Fix/check empty password

### LINKED ISSUE #660: Inconsistent behavior when manipulating app args
**Describe the bug**

When setting the secure mode for the VPN-server via HypervisorUI and without setting a password, the hypervisor UI adds these values

```
		"name": "vpn-server",
				"args": [
					"-passcode",
					"",
					"-secure",
					"true"
				],
```

This leads to the VPN-server not registering itself in the service discovery because the check we perform is not sufficient. This needs to be fixed. 

When unchecking the box of secure mode again, this is the updated config value: 

```
	"name": "vpn-server",
				"args": [
					"-secure",
					"false"
				],
```

This is probably not the best way to deal with it. Imo, it sounds cleaner to generate the default values at config generation and always update all of the values when manipulating at least one of them via the hypervisor. The check for whether the VPN is password protected needs to be improved to actually check whether the password is non-empty instead of just checking if the arg is present.

### PR DESCRIPTION
**Pull request by jdknives**
Did you run `make format && make check`?

Yes

Fixes #660 at least the bug. The inconsistency remains. 

 Changes:	
- adds check to verify if password is empty. If password is empty, the appupdater is being created. Previously empty string password would lead to appdiscupdater not being created which is not the correct behavior. 

How to test this PR:

- run VPN-server with passcode arg set to empty string against prod deployment
- verify the VPN server gets registered here: https://service.discovery.skycoin.com/api/services?type=vpn

### CODE REVIEW

File: pkg/app/appdisc/factory.go [hunk 1]
```diff
@@ -124,3 +124,13 @@ func argEqualsFlag(arg, flag string) bool {
 
 	return arg == flag
 }
+
+func argVal(args []string, flag string) string {
+	for idx, arg := range args {
+		if argEqualsFlag(arg, flag) {
+			return args[idx+1]
```
Comment (Darkren) [inline pkg/app/appdisc/factory.go]: I'm not sure, but if we pass `--passcode` as the last flag without value, wouldn't it panic with the `index out of bounds`? probably it's worth checking in here that `id < len(args)`. otherwise the value should be considered empty

**Review by Darkren — CHANGES_REQUESTED** [review]
Great job! But I'm afraid it may panic. Not sure though

File: pkg/app/appdisc/factory.go (hunk 1 above)
Comment (jdknives) [reply pkg/app/appdisc/factory.go]: Added check.

**Review by i-hate-nicknames — COMMENTED** [review]
Great job! I would move argVal function to pkg/app/appcommon/proc_config.go, since it's a generic arg operation

**Comment by jdknives** [comment]
> Great job! I would move argVal function to pkg/app/appcommon/proc_config.go, since it's a generic arg operation

Probably a good idea. will do that.

**Review by Darkren — APPROVED** [review]
