### PR TITLE
Fix VPN apps

### LINKED ISSUE #378: VPN client fails to start macOS
**Describe the bug**
When running the VPN client on macOS, the following error is thrown: 

```
[2020-05-28T19:18:22.954344+08:00] INFO (STDERR) [proc:vpn-client:b789b31decb944b18304f672129af205]: time="2020-05-28T19:18:22+08:00" level=fatal msg="Error creating VPN client" error="error getting Dmsg discovery IP: env arg ADDR_DMSG_DISC is not provided"
```

A second error was thrown on a different machine: 

```
2020/05/29 14:10:14 [ERR] yamux: keepalive failed: i/o deadline reached
[2020-05-29T14:10:14+03:00] WARN [snet.dmsgC]: Stopped accepting streams. error="keepalive timeout" session=035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282
[2020-05-29T14:10:14+03:00] INFO [snet.dmsgC]: Session stopped. error="failed to serve dialed session to 035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282: keepalive timeout"
[2020-05-29T14:10:14+03:00] INFO [snet.dmsgC]: Updating entry. entry=    version: 0.0.1
```

**Environment information:**

- OS: e.g. macOS 

**Steps to Reproduce**

1. Checkout `develop`
2. Use the attached config. 
3. Start visor with sudo privileges.
4. Establish tp to remote passed to VPN client
5. Start VPN client

```
{
	"version": "v1.0.0",
	"sk": "c074593bc6b98ce797ce6242cfba5f0912f9c46f60533c673518928df4ebf583",
	"pk": "021a9935d60b81d248d25104c5f8ee9a2a26bf545d21e3f3d481b36269ee6f8718",
	"dmsg": {
		"discovery": "http://dmsg.discovery.skywire.cc",
		"sessions_count": 1
	},
	"dmsgpty": {
		"port": 22,
		"authorization_file": "./dmsgpty/whitelist.json",
		"cli_network": "unix",
		"cli_address": "/tmp/dmsgpty.sock"
	},
	"stcp": {
		"pk_table": {
			"03302d940c9b95afa43897df7626c4773624a5b3185fa65ccb88fb9302f2d154c3": "172.104.103.48:7777"
		},
		"local_address": ":7777"
	},
	"transport": {
		"discovery": "http://transport.discovery.skywire.cc",
		"log_store": {
			"type": "file",
			"location": "./transport_logs"
		},
		"trusted_visors": null
	},
	"routing": {
		"setup_nodes": [
			"026c5a07de617c5c488195b76e8671bf9e7ee654d0633933e202af9e111ffa358d"
		],
		"route_finder": "http://routefinder.skywire.cc",
		"route_finder_timeout": "10s"
	},
	"uptime_tracker": {
		"addr": "http://uptime-tracker.skywire.cc"
	},
	"launcher": {
		"discovery": {
			"update_interval": "30s",
			"proxy_discovery_addr": "http://proxy.discovery.skywire.cc"
		},
		"apps": [
			{
				"name": "skychat",
				"args": [
					"-addr",
					":8001"
				],
				"auto_start": true,
				"port": 1
			},
			{
				"name": "skysocks",
				"auto_start": true,
				"port": 3
			},
			{
				"name": "skysocks-client",
				"auto_start": false,
				"port": 13
			},
			{
				"name": "vpn-server",
				"auto_start": false,
				"port": 44
			},
			{
				"name": "vpn-client",
				"args": [
					"-srv",
					"02c61b06ad757c50ffe31e9d3e7873bb8cb990ec4c6995c5c6c1590601728bc413",
					"-sk",
					"c074593bc6b98ce797ce6242cfba5f0912f9c46f60533c673518928df4ebf583"
				],
				"auto_start": false,
				"port": 43
			}
		],
		"server_addr": "localhost:5505",
		"bin_path": "./apps",
		"local_path": "./local"
	},
	"hypervisors": null,
	"cli_addr": "localhost:3435",
	"log_level": "info",
	"shutdown_timeout": "10s",
	"restart_check_delay": "1s"
```

### PR DESCRIPTION
**Pull request by Darkren**
Did you run `make format && make check`?
Yes
Fixes #378 	

 Changes:	
- Fixed ticker panic in discovery updater

### CODE REVIEW

**Review by jdknives — APPROVED** [review]
Fixes the panic.

**Review by nkryuchkov — APPROVED** [review]

File: .gitignore [hunk 1]
```diff
@@ -11,7 +11,7 @@
 .idea/
 
 /skywire.json
-/apps/
+#/apps/
```
Comment (nkryuchkov) [inline .gitignore]: Could we remove it?

File: .gitignore [hunk 2]
```diff
@@ -24,7 +24,7 @@ pkg/visor/foo/
 /users.db
 /hypervisor
 /*-node
-/*-visor
+#/*-visor
```
Comment (nkryuchkov) [inline .gitignore]: Could we remove it?

File: internal/vpn/client.go [hunk 3]
```diff
@@ -58,21 +58,35 @@ func NewClient(cfg ClientConfig, l logrus.FieldLogger, conn net.Conn) (*Client,
...
+	if _, ok := os.LookupEnv(STCPHAddressResolverAddrEnvKey); ok {
+		stcphARip, err = stcphAddressResolverIPFromEnv()
+		if err != nil {
+			return nil, fmt.Errorf("error getting stcph AR IP: %w", err)
+		}
 	}
 
-	directIPs := make([]net.IP, 0, 5+len(dmsgSrvAddrs)+len(stcpEntities))
-	directIPs = append(directIPs, dmsgDiscIP, tpDiscIP, rfIP, stcprARip, stcphARip)
+	directIPs := make([]net.IP, 0, 3+len(dmsgSrvAddrs)+len(stcpEntities))
```
Comment (nkryuchkov) [inline internal/vpn/client.go]: What do you think about creating a slice that contains `dmsgDiscIP, tpDiscIP, rfIP` and replacing `3` with its length? I'm afraid it may be easy to miss updating `3` if a service with a direct IP is added in the future.

File: pkg/app/appdisc/discovery_updater.go [hunk 4]
```diff
@@ -29,8 +29,8 @@ func (emptyUpdater) Start()                                  {}
 func (emptyUpdater) Stop()                                   {}
 func (emptyUpdater) ChangeValue(name string, v []byte) error { return nil }
 
-// proxyUpdater updates proxy-discovery entry of locally running skysocks App.
-type proxyUpdater struct {
+// serviceUpdater updates service-discovery entry of locally running App.
```
Comment (nkryuchkov) [inline pkg/app/appdisc/discovery_updater.go:32]: Service discovery is still named proxy discovery throughout the project. I think we need to change the occurrences either here or in this PR: https://github.com/SkycoinProject/skywire-mainnet/pull/393. Please let me know your decision.

Comment (Darkren) [reply pkg/app/appdisc/discovery_updater.go:32]: This is just one thing I bumped into, not sure that here's the right place to fix it. so, go ahead with it

File: internal/vpn/client.go (hunk 3 above)
Comment (Darkren) [reply internal/vpn/client.go]: Done that

**Review by nkryuchkov — APPROVED** [review]
