### PR TITLE
Verify public key before requesting routes

### LINKED ISSUE #172: It is possible to request routes to invalid public keys.
**Describe the bug**
It is possible to request routes to invalid public keys. The current example is to empty public keys.
```
[2020-02-29T01:07:24+08:00] INFO [router]: Requesting new routes from 031b80cd5773143a39d940dc0710b93dcccc262a85108018a7a95ab9af734f8055 to 000000000000000000000000000000000000000000000000000000000000000000
[2020-02-29T01:07:34+08:00] INFO [skychat.v1.0[ERROR]]: time="2020-02-29T01:07:34+08:00" level=warning msg="route finder: transport not found" source="retrier.go:68"
```
**Environment**:
- `skywire-services@feature/m3-dmsgpty-hypervisor`
- `skywire-mainnet@evanlinjin:feature/m3-dmsgpty-hypervisor`
- `dmsg@mainnet-milestone2`

**Steps to Reproduce**
1. Run the [generic integration environment](https://github.com/SkycoinPro/skywire-services/blob/5b5de57c99e5693a3c62fac8c7e9e954d1371070/Makefile#L121).
2. Run `make integration-startup` to setup transports.
3. Open http://localhost:8000/ in browser and type a random message. Check logs of associated visor.

**Actual behavior**
```
[2020-02-29T01:07:24+08:00] INFO [router]: Requesting new routes from 031b80cd5773143a39d940dc0710b93dcccc262a85108018a7a95ab9af734f8055 to 000000000000000000000000000000000000000000000000000000000000000000
[2020-02-29T01:07:34+08:00] INFO [skychat.v1.0[ERROR]]: time="2020-02-29T01:07:34+08:00" level=warning msg="route finder: transport not found" source="retrier.go:68"
```
**Expected behavior**
The visor shouldn't waste time with such new routes.

**Possible implementation**
Look in router (maybe).

### PR DESCRIPTION
**Pull request by Kifen**
Did you run `make format && make check`?
Yes
Fixes #172 	

 Changes:	
-	Verified public key before call to `(*router).DialContext` in `(*SkywireNetworker).DialContext`

How to test this PR: Run the integaration-env, run`make integration-startup`, open [http://localhost:8000/](http://localhost:8000/) and type a message. Then check associated visor for logs.

### CODE REVIEW

File: pkg/app/appnet/skywire_networker.go [hunk 1]
```diff
@@ -50,7 +51,12 @@ func (r *SkywireNetworker) DialContext(ctx context.Context, addr Addr) (net.Conn
 		return nil, err
 	}
 
-	rg, err := r.r.DialRoutes(ctx, addr.PubKey, routing.Port(localPort), addr.Port, router.DefaultDialOptions())
+	rPK := addr.PubKey
+	if rPK.Null() {
+		return nil, fmt.Errorf("Empty public key: %s", rPK)
```
Comment (evanlinjin) [inline pkg/app/appnet/skywire_networker.go]: Please change to this:
```golang
return nil, errors.New("cannot dial to address with empty public key")
```
- Golang errors should always start with a lowercase letter.
- If the public key is empty, we don't need to show it in the error message. It is empty after all.

**Review by evanlinjin — CHANGES_REQUESTED** [review]

File: pkg/app/appnet/skywire_networker.go (hunk 1 above)
Comment (Kifen) [reply pkg/app/appnet/skywire_networker.go]: Right. Refactored the error.
