### PR TITLE
fixing VPN server problem with multiple network interface

### LINKED ISSUE #1145: VPN server doesn't work if the machine is connected via lan and wifi
**Describe the bug**
The app vpn-server doesn't start if the machine it is running on is has a plan connection as well as wifi. It will work if the machine is connected to either one.

**Environment information:**

- OS: e.g. Linux
- Platform: Linux 5.13.0-39-generic x86_64

**Steps to Reproduce**

1. Connect the machine to internet via lan
2. Connect to a wifi router
3. Start visor `sudo ./skywire-visor -c skywire-config.json`
4. Start the `vpn-server` from the hypervisor UI
5. See error

**Actual behavior**
```
[2022-04-06T18:02:38+05:30] INFO [proc_manager]: Accepted proc conn. hello="{"proc_key":"e78744fae76d4c1f9a64eea315749c7e"}" remote=127.0.0.1:39642
[2022-04-06T18:02:38+05:30] INFO [proc:vpn-server:e78744fae76d4c1f9a64eea315749c7e]: Associated and serving proc conn.
[2022-04-06T18:02:39+05:30] INFO [proc:vpn-server:e78744fae76d4c1f9a64eea315749c7e]: Request processed. _elapsed="920.254µs" _method="Listen" _received="6:02PM" input=038a33fc20b568b3e40f0bba1ab4ebd9eba938e33eb1d0904ccad1320911be7643:44 output=0xc002b1829e
[2022-04-06T18:02:39+05:30] INFO (STDERR) [proc:vpn-server:e78744fae76d4c1f9a64eea315749c7e]: time="2022-04-06T18:02:39+05:30" level=info msg="Got app listener, bound to 44"
[2022-04-06T18:02:39+05:30] INFO (STDOUT) [proc:vpn-server:e78744fae76d4c1f9a64eea315749c7e]: net.ipv4.ip_forward = 1
[2022-04-06T18:02:39+05:30] INFO (STDERR) [proc:vpn-server:e78744fae76d4c1f9a64eea315749c7e]: time="2022-04-06T18:02:39+05:30" level=info msg="Got default network interface: enp4s0\nwlp5s0"
[2022-04-06T18:02:39+05:30] INFO [proc:vpn-server:e78744fae76d4c1f9a64eea315749c7e]: Request processed. _elapsed="7.844µs" _method="CloseConn" _received="6:02PM" input=0xc0028f4c98
[2022-04-06T18:02:39+05:30] INFO (STDOUT) [proc:vpn-server:e78744fae76d4c1f9a64eea315749c7e]: net.ipv6.conf.all.forwarding = 1
[2022-04-06T18:02:39+05:30] INFO (STDERR) [proc:vpn-server:e78744fae76d4c1f9a64eea315749c7e]: time="2022-04-06T18:02:39+05:30" level=info msg="Got IPs of interface enp4s0\nwlp5s0: []"
[2022-04-06T18:02:39+05:30] INFO (STDOUT) [proc:vpn-server:e78744fae76d4c1f9a64eea315749c7e]: net.ipv6.conf.all.forwarding = 1
[2022-04-06T18:02:39+05:30] INFO (STDERR) [proc:vpn-server:e78744fae76d4c1f9a64eea315749c7e]: time="2022-04-06T18:02:39+05:30" level=info msg="Old IP forwarding values:"
[2022-04-06T18:02:39+05:30] INFO (STDOUT) [proc:vpn-server:e78744fae76d4c1f9a64eea315749c7e]: net.ipv4.ip_forward = 1
[2022-04-06T18:02:39+05:30] INFO (STDERR) [proc:vpn-server:e78744fae76d4c1f9a64eea315749c7e]: time="2022-04-06T18:02:39+05:30" level=info msg="IPv4: 1, IPv6: 1"
[2022-04-06T18:02:39+05:30] INFO (STDERR) [proc:vpn-server:e78744fae76d4c1f9a64eea315749c7e]: time="2022-04-06T18:02:39+05:30" level=info msg="Old iptables forward policy: ACCEPT"
[2022-04-06T18:02:39+05:30] INFO (STDERR) [proc:vpn-server:e78744fae76d4c1f9a64eea315749c7e]: time="2022-04-06T18:02:39+05:30" level=info msg="Set IPv4 forwarding = 1"
[2022-04-06T18:02:39+05:30] INFO (STDERR) [proc:vpn-server:e78744fae76d4c1f9a64eea315749c7e]: time="2022-04-06T18:02:39+05:30" level=info msg="Set IPv6 forwarding = 1"
[2022-04-06T18:02:39+05:30] INFO (STDERR) [proc:vpn-server:e78744fae76d4c1f9a64eea315749c7e]: sh: 2: wlp5s0: not found
[2022-04-06T18:02:39+05:30] INFO (STDERR) [proc:vpn-server:e78744fae76d4c1f9a64eea315749c7e]: time="2022-04-06T18:02:39+05:30" level=info msg="Set IPv6 forwarding = 1"
[2022-04-06T18:02:39+05:30] INFO (STDERR) [proc:vpn-server:e78744fae76d4c1f9a64eea315749c7e]: time="2022-04-06T18:02:39+05:30" level=info msg="Set IPv4 forwarding = 1"
[2022-04-06T18:02:39+05:30] INFO (STDERR) [proc:vpn-server:e78744fae76d4c1f9a64eea315749c7e]: time="2022-04-06T18:02:39+05:30" level=error msg="Error serving" error="error enabling IP masquerading for enp4s0\nwlp5s0: error running command \"sh -c iptables -t nat -A POSTROUTING -o enp4s0\nwlp5s0 -j MASQUERADE\": exit status 127: sh: 2: wlp5s0: not found\n"
```

### PR DESCRIPTION
**Pull request by mrpalide**
Did you run `make format && make check`? Yes

Fixes #1145

 Changes:	
- add new argument to vpn-server `-netifc`
- add cli related command

How to test this PR:
- check you have more than one default network interface by `ip r` command, if not make it.
- `make build`
- start vpn-server from UI and check logs, you should see an error like this:
  `[2022-04-19T04:45:50+04:30] INFO (STDERR) [proc:vpn-server:8ba78bc35b91411081c546dbb5ca1edd]: time="2022-04-19T04:45:50+04:30" level=fatal msg="Error creating VPN server" error="multiple default network interface detected, please set once in setting or be single: [enp0s20u3 wlp7s0]"`
- set `-netifc` argument in vpn-server part of config
- start vpn-server again, and would start normaly
- actually, you can set it by `skywire-cli config update vpns --netifc xxx` [Not work now, get an error `FATAL []: Failed to parse config. error="open : no such file or directory"`, need handle by @0pcom help ]
- and, you can set it by hypervisor UI too [need #1158]

### CODE REVIEW

File: internal/vpn/server.go [hunk 1]
```diff
@@ -29,15 +30,25 @@ type Server struct {
...
-	if err != nil {
-		return nil, fmt.Errorf("error getting default network interface: %w", err)
+	if cfg.NetworkInteface == "" {
+		defaultNetworkIfcs, err := netutil.DefaultNetworkInterface()
+		if err != nil {
+			return nil, fmt.Errorf("error getting default network interface: %w", err)
+		}
+		netIfcs, isMultiple := s.checkingNetworkInterface(defaultNetworkIfcs)
+		if isMultiple {
+			return nil, fmt.Errorf("multiple default network interface detected, please set once in setting or be single: %v", netIfcs)
```
Comment (jdknives) [inline internal/vpn/server.go]: "multiple default network interfaces detected...set a default one for VPN server or remove one: %v"

File: internal/vpn/server.go [hunk 2]
```diff
@@ -29,15 +30,25 @@ type Server struct {
...
+		}
+		defaultNetworkIfc = defaultNetworkIfcs
+	} else {
+		defaultNetworkIfc = cfg.NetworkInteface
```
Comment (jdknives) [inline internal/vpn/server.go]: NetworkInterface

File: internal/vpn/server.go (hunk 1 above)
Comment (jdknives) [reply internal/vpn/server.go]: Maybe 

`ifcs, hasMultiple := s.hasMutipleNetworkInterfaces(...)`

**Comment by jdknives** [comment]
Haven't tested it myself, but if it works, its almost good to go.

File: internal/vpn/server.go (hunk 1 above)
Comment (mrpalide) [reply internal/vpn/server.go]: Done.

File: internal/vpn/server.go (hunk 2 above)
Comment (mrpalide) [reply internal/vpn/server.go]: Done.

File: cmd/skywire-cli/commands/config/update/update.go [hunk 3]
```diff
@@ -200,6 +201,9 @@ var vpnServerUpdateCmd = &cobra.Command{
 		if addVPNServerPasscode != "" {
 			changeAppsConfig(conf, "vpn-server", "--passcode", addVPNServerPasscode)
 		}
+		if setVPNServerNetIfc != "" {
+			changeAppsConfig(conf, "vpn-server", "-netifc", setVPNServerNetIfc)
```
Comment (ersonp) [inline cmd/skywire-cli/commands/config/update/update.go:205]: Shouldn't this be `--netifc` instead of `-netifc`

**Comment by ersonp** [comment]
We need to add a check for the value of `-netifc` and it should be equal to the available interfaces. Currently we can pass anything it it for example
```
			{
				"name": "vpn-server",
				"args": [
					"-netifc",
					"asdasdasd"
				],
				"auto_start": false,
				"port": 44
			}
```
and it works.
```
[2022-04-22T13:52:20+05:30] INFO (STDERR) [proc:vpn-server:5937f58c91eb4e59a409c757314d6b30]: time="2022-04-22T13:52:20+05:30" level=info msg="Got default network interface: asdasdasd"
[2022-04-22T13:52:20+05:30] INFO (STDERR) [proc:vpn-server:5937f58c91eb4e59a409c757314d6b30]: time="2022-04-22T13:52:20+05:30" level=info msg="Got IPs of interface asdasdasd: []"
```

File: cmd/skywire-cli/commands/config/update/update.go (hunk 3 above)
Comment (ersonp) [inline cmd/skywire-cli/commands/config/update/update.go]: It should be `--netifc` and not `-netifc`

**Comment by ersonp** [comment]
We should also add this error 
```
[2022-04-22T14:08:04+05:30] INFO (STDERR) [proc:vpn-server:9a887a337a1148edb8292ef4081421f1]: time="2022-04-22T14:08:04+05:30" level=fatal msg="Error creating VPN server" error="multiple default network interfaces detected...set a default one for VPN server or remove one: [enp4s0 wlp5s0]
```
to proc errors just like the vpn-client adds it's errors.

File: cmd/skywire-cli/commands/config/update/update.go (hunk 3 above)
Comment (mrpalide) [reply cmd/skywire-cli/commands/config/update/update.go]: Done.

**Comment by mrpalide** [comment]
> We should also add this error
> 
> ```
> [2022-04-22T14:08:04+05:30] INFO (STDERR) [proc:vpn-server:9a887a337a1148edb8292ef4081421f1]: time="2022-04-22T14:08:04+05:30" level=fatal msg="Error creating VPN server" error="multiple default network interfaces detected...set a default one for VPN server or remove one: [enp4s0 wlp5s0]
> ```
> 
> to proc errors just like the vpn-client adds it's errors.

Because mostly usage of vpn-server is on instances without GUI, I think this feature is not urgent for this release, so I make ticket for this [#1163].

**Review by ersonp — APPROVED** [review]
