### PR TITLE
Setup node metrics.

### LINKED ISSUE #405: Metrics for setup-node.
We need [Prometheus](https://prometheus.io/) metrics reporting for `setup-node`.

### Metrics
- [x] Gauge for ongoing request count.
- [x] Histogram for request duration.
- [x] Counters for failed and successful requests.

### PR DESCRIPTION
**Pull request by evanlinjin**
Fixes #405 

Changes:	
- Re-implemented how metrics are handled.
- Updated .gitignore

How to test this PR:
- Start `setup-node` with flag `-m :2121`
- Navigate to `http://localhost:2121/metrics`

### CODE REVIEW

**Comment by jdknives** [comment]
@evanlinjin binaries are still there.

File: cmd/setup-node/commands/root.go [hunk 1]
```diff
@@ -60,52 +70,62 @@ var rootCmd = &cobra.Command{
...
+	go func() { log.Fatal(http.ListenAndServe(metricsAddr, mux)) }()
+
+	return m
 }
 
 // Execute executes root CLI command.
 func Execute() {
 	if err := rootCmd.Execute(); err != nil {
-		log.Fatal(err)
+		panic(err)
```
Comment (Darkren) [inline cmd/setup-node/commands/root.go:129]: Why do you think this change is necessary?

File: pkg/setup/setupmetrics/metrics.go [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+		m.reqDurations,
+	}
+}
+
+func (m *metrics) RecordRequest(_ routing.BidirectionalRoute) func(rules *routing.EdgeRules, err *error) {
+	start := time.Now()
+	m.activeRequests.Inc()
+
+	return func(rules *routing.EdgeRules, err *error) {
+		var successStr string
```
Comment (Darkren) [inline pkg/setup/setupmetrics/metrics.go]: we may simplify this part a bit with something like this:
```
successStr := "true"
if *err != nil {
    successStr = "false"
}
```

btw, is it neccessary to have interface pointer in the func signature, wouldn't just `error` be enough here?

**Review by Darkren — CHANGES_REQUESTED** [review]
Few minor questions, but otherwise - great job! Also, could you please remove transport logs?

File: cmd/setup-node/commands/root.go (hunk 1 above)
Comment (evanlinjin) [reply cmd/setup-node/commands/root.go:129]: `log.Fatal` logs the error and then panics. However, when a `cobra.Command` fails, it already logs the error. So we only need to panic here.

File: pkg/setup/setupmetrics/metrics.go (hunk 2 above)
Comment (evanlinjin) [reply pkg/setup/setupmetrics/metrics.go]: That code looks cleaner. I'll get it done.

The pointer of an `error` is needed. We need to get the pointer of the error, as the error value will change.
