### PR TITLE
Fix update endpoint.

### LINKED ISSUE #213: Cannot update call update endpoint twice.
**Describe the bug**
Cannot call the hypervisor `/api/visors/{visor-pk}/update` endpoint twice for a given `visor` without resulting in `500 - {"error":"updating already started"}` error.

**Environment information:**
Independent, interactive generic environment.

### PR DESCRIPTION
**Pull request by evanlinjin**
Fixes #213

 Changes:	
* Added defer statement to Updater.Update to revert u.updating value back to 0 after updating.
* Make `restart.Context` reset it's internal `exec.Cmd` on failure.
* Changed restart visor endpoint to only accept `POST`.
* Update `restart.Restart` test.

### CODE REVIEW

**Review by jdknives — APPROVED** [review]
Cannot reproduce the error anymore.

File: pkg/restart/restart.go [hunk 1]
```diff
@@ -70,24 +72,28 @@ func (c *Context) CmdPath() string {
...
-	defer ticker.Stop()
 
 	select {
-	case err := <-errCh:
+	case err = <-errCh:
 		c.errorLogger()("Failed to start new instance: %v", err)
-		return err
+
+		// Reset c.cmd on failure so it can be reused.
+		c.cmd = captureCmd()
```
Comment (nkryuchkov) [inline pkg/restart/restart.go]: I would copy the necessary fields from one `exec.Command` to another because data to be captured can be changed while the process is run. We are not going to change the data, but I think copying `exec.Command` is more robust.

**Review by nkryuchkov — APPROVED** [review]
Good job!
