### PR TITLE
Increase backoff factor and limit

### LINKED ISSUE #712: Improve stcpr redialing logic
**Describe the bug**
If a `stcpr` transport is registered in the `tp-disc` but the transport between the two visors cannot actually be established, the visor tries to dial over and over again. It should probably use a backoff. 

```
[2021-03-10T20:44:04-03:00] INFO [stcpr]: Dialing PK 03924a9a5fa350949ad668bcad82c49cec24a371853e3b6c90077d0999ade5c7de
[2021-03-10T20:44:05-03:00] INFO [stcpr]: Resolved PK 03924a9a5fa350949ad668bcad82c49cec24a371853e3b6c90077d0999ade5c7de to visor data {172.105.249.154 false {44159 [127.0.0.1 172.105.249.154 ::1 2a01:7e01::f03c:92ff:fe23:7806]}}
[2021-03-10T20:44:06-03:00] INFO [stcpr]: Dialing PK 03924a9a5fa350949ad668bcad82c49cec24a371853e3b6c90077d0999ade5c7de
[2021-03-10T20:44:07-03:00] INFO [stcpr]: Resolved PK 03924a9a5fa350949ad668bcad82c49cec24a371853e3b6c90077d0999ade5c7de to visor data {172.105.249.154 false {44159 [127.0.0.1 172.105.249.154 ::1 2a01:7e01::f03c:92ff:fe23:7806]}}
[2021-03-10T20:44:08-03:00] INFO [stcpr]: Dialing PK 03924a9a5fa350949ad668bcad82c49cec24a371853e3b6c90077d0999ade5c7de
[2021-03-10T20:44:09-03:00] INFO [stcpr]: Resolved PK 03924a9a5fa350949ad668bcad82c49cec24a371853e3b6c90077d0999ade5c7de to visor data {172.105.249.154 false {44159 [127.0.0.1 172.105.249.154 ::1 2a01:7e01::f03c:92ff:fe23:7806]}}
[2021-03-10T20:44:11-03:00] INFO [stcpr]: Dialing PK 03924a9a5fa350949ad668bcad82c49cec24a371853e3b6c90077d0999ade5c7de
[2021-03-10T20:44:11-03:00] INFO [stcpr]: Resolved PK 03924a9a5fa350949ad668bcad82c49cec24a371853e3b6c90077d0999ade5c7de to visor data {172.105.249.154 false {44159 [127.0.0.1 172.105.249.154 ::1 2a01:7e01::f03c:92ff:fe23:7806]}}
[2021-03-10T20:44:14-03:00] INFO [stcpr]: Dialing PK 03924a9a5fa350949ad668bcad82c49cec24a371853e3b6c90077d0999ade5c7de
[2021-03-10T20:44:14-03:00] INFO [stcpr]: Resolved PK 03924a9a5fa350949ad668bcad82c49cec24a371853e3b6c90077d0999ade5c7de to visor data {172.105.249.154 false {44159 [127.0.0.1 172.105.249.154 ::1 2a01:7e01::f03c:92ff:fe23:7806]}}
[2021-03-10T20:44:18-03:00] INFO [stcpr]: Dialing PK 03924a9a5fa350949ad668bcad82c49cec24a371853e3b6c90077d0999ade5c7de
[2021-03-10T20:44:19-03:00] INFO [stcpr]: Resolved PK 03924a9a5fa350949ad668bcad82c49cec24a371853e3b6c90077d0999ade5c7de to visor data {172.105.249.154 false {44159 [127.0.0.1 172.105.249.154 ::1 2a01:7e01::f03c:92ff:fe23:7806]}}
```

### PR DESCRIPTION
**Pull request by Darkren**
Did you run `make format && make check`?

Fixes #712 

 Changes:	
- Maximum backoff and multiplication factor for tp redialing backoff were increased to 1 minute and 2 respectively

### CODE REVIEW

File: pkg/transport/managed_transport.go [hunk 1]
```diff
@@ -38,9 +38,9 @@ var (
 // @evanlinjin: I see no need to make these configurable.
```
Comment (jdknives) [inline pkg/transport/managed_transport.go]: Not part of your PR, but this comment is redundant imo.
