### PR TITLE
Remove some panics

### LINKED ISSUE #186: Get rid of panics where possible
We have a lot of `panic()`'s in the codebase. They often fire unexpectedly, usually in tests, but also may do in production, which is unsafe. Moreover, they are a code smell (https://github.com/golang/go/wiki/CodeReviewComments#dont-panic). So, `panic()`'s are to be rewritten into returning or logging errors wherever it's possible.

This should be done in the following repositories:

- [x] https://github.com/SkycoinProject/skywire-mainnet

- [x] https://github.com/SkycoinPro/skywire-services

- [ ] https://github.com/SkycoinProject/dmsg

### PR DESCRIPTION
**Pull request by nkryuchkov**
Did you run `make format && make check`? yes

Partially fixes #186 

 Changes:	
- Remove some panics

How to test this PR:
`make check`

### CODE REVIEW

File: pkg/transport/managed_transport.go [hunk 1]
```diff
@@ -412,7 +412,7 @@ func (mt *ManagedTransport) clearConn() {
 
 func (mt *ManagedTransport) updateStatus(isUp bool, tries int) (err error) {
 	if tries < 1 {
-		panic(fmt.Errorf("mt.updateStatus: invalid input: got tries=%d (want tries > 0)", tries))
```
Comment (evanlinjin) [inline pkg/transport/managed_transport.go]: I feel a panic here is appropriate because it signals the developer that an invalid input is provided.
And the new error message is not clear and will be hard to track where the error came from.

File: pkg/snet/network.go [hunk 2]
```diff
@@ -263,18 +279,24 @@ func (c Conn) RemotePort() uint16 { return c.rPort }
 // Network returns network of connection.
 func (c Conn) Network() string { return c.network }
 
-func disassembleAddr(addr net.Addr) (pk cipher.PubKey, port uint16) {
+func disassembleAddr(addr net.Addr) (pk cipher.PubKey, port uint16, retErr error) {
 	strs := strings.Split(addr.String(), ":")
 	if len(strs) != 2 {
-		panic(fmt.Errorf("network.disassembleAddr: %v %s", "invalid addr", addr.String()))
```
Comment (evanlinjin) [inline pkg/snet/network.go:269]: I feel like panics here are appropriate, because is the `addr` cannot be disassembled to `pk:port`, it signals an invalid `snet.Conn`.

File: pkg/visor/rpc.go [hunk 3]
```diff
@@ -42,16 +42,18 @@ type RPC struct {
...
+func newRPCServer(v *Visor, remoteName string) (*rpc.Server, error) {
 	rpcS := rpc.NewServer()
 	rpcG := &RPC{
 		visor: v,
 		log:   v.Logger.PackageLogger("visor_rpc:" + remoteName),
 	}
+
 	if err := rpcS.RegisterName(RPCPrefix, rpcG); err != nil {
-		panic(fmt.Errorf("failed to create visor RPC server: %v", err))
+		return nil, fmt.Errorf("failed to create visor RPC server: %v", err)
```
Comment (evanlinjin) [inline pkg/visor/rpc.go:53]: I feel this should panic, as it signals a problem with the `rpcG` implementation.

**Review by evanlinjin — CHANGES_REQUESTED** [review]
I feel some panics are appropriate. I think panics should be used to identify issues with the use of code base.

File: pkg/snet/network.go (hunk 2 above)
Comment (Darkren) [reply pkg/snet/network.go:269]: This may happen if one of our subsystems implements `net.Addr` the wrong way, the way we consider wrong. So, I'd stick to panic in this particular case, cause it will raise only on first test runs and will help us identify error fast instead of looking through logs

File: pkg/transport/managed_transport.go (hunk 1 above)
Comment (Darkren) [reply pkg/transport/managed_transport.go]: Probably it would be better if we just go for `uint` tries values here. We're calling this func passing `tries` as a raw number, not a variable, so no type conversions will be needed. And we won't need to decide on panic/error here

Comment (Darkren) [reply pkg/transport/managed_transport.go]: Also, if we go with `uint` tries, we should change tries loop condition check inclusive down the code

File: pkg/visor/rpc.go (hunk 3 above)
Comment (Darkren) [reply pkg/visor/rpc.go:53]: Personally, I think error will be more suitable in such cases, cause it gets wrapped, and we're going `log.Fatal` in the outer code anyway. This way error will be easier to understand in logs

File: pkg/transport/managed_transport.go (hunk 1 above)
Comment (evanlinjin) [reply pkg/transport/managed_transport.go]: That's a good point. Thank you @Darkren

File: pkg/visor/rpc.go (hunk 3 above)
Comment (evanlinjin) [reply pkg/visor/rpc.go:53]: But panic will direct us to exactly which line it panicked.

File: pkg/snet/network.go (hunk 2 above)
Comment (nkryuchkov) [reply pkg/snet/network.go:269]: @evanlinjin @Darkren Thanks for your opinions. I agree.

File: pkg/visor/rpc.go (hunk 3 above)
Comment (nkryuchkov) [reply pkg/visor/rpc.go:53]: Let's leave panic here. I don't think that an error will give us big benefits.

File: pkg/transport/managed_transport.go (hunk 1 above)
Comment (nkryuchkov) [reply pkg/transport/managed_transport.go]: I'm going to leave panic here.

**Review by evanlinjin — APPROVED** [review]
Good.
